version: "3"

includes:
  examples:
    taskfile: ./examples/Taskfile.yml
    dir: ./examples

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  build:
    desc: Build the CLI binary
    cmds:
      - go build -o bin/stowry ./cmd/stowry

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test:verbose:
    desc: Run all tests with verbose output
    cmds:
      - go test -v ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  check:
    desc: Format, lint, and test
    cmds:
      - task: fmt
      - task: lint
      - task: test

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/

  tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t stowry:test .

  docker:test:
    desc: Build and run Docker container for testing
    deps: [docker:build]
    cmds:
      - docker run --rm -p 5708:5708 -e STOWRY_DATABASE_TYPE=sqlite -e STOWRY_STORAGE_PATH=/data stowry:test serve --db-dsn ":memory:"