version: "3"

tasks:
  default:
    desc: Run the Next.js app in development mode
    deps: [deps]
    cmds:
      - npm run dev

  deps:
    desc: Install dependencies
    cmds:
      - npm install
    sources:
      - package.json
    generates:
      - node_modules/**/*

  build:
    desc: Build for production
    deps: [deps]
    cmds:
      - npm run build

  start:
    desc: Start production server
    deps: [build]
    cmds:
      - npm start

  lint:
    desc: Run linter
    deps: [deps]
    cmds:
      - npm run lint

  clean:
    desc: Remove build artifacts and node_modules
    cmds:
      - rm -rf node_modules .next